general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/rose-pine.toml"
  # "~/.config/alacritty/rose-pine-moon.toml"
  "~/.config/alacritty/tokyo-night.toml"
  # "~/.config/alacritty/tokyo-night-storm.toml"
]

[env]
TERM = "xterm-256color"

# [[ Font ]]
# JetbrainsMono Nerd Font
# Monaspace Neon
# MonoLisa Nerd Font
# CommitMono Nerd Font
# FiraCode Nerd Font
# Maple Mono NF
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
bold_italic = { style = "Bold Italic" }
italic = { style = "Italic" }
size = 14
offset.y = 1

[cursor]
style = { blinking = "On" }
