import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = {family = "FiraCode Nerd Font Mono", style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono"}
size = 15

[cursor]
style = { blinking = "On" }
