import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

# Cousine Nerd Font Mono
# LiterationMono Nerd Font
# JetbrainsMono
# FiraCode 
# RobotoMono Nerd Font Mono
[font]
normal = { family = "Cousine Nerd Font Mono", style = "Regular" }
bold = { family = "Cousine Nerd Font Mono", style = "Bold" }
bold_italic = { family = "Cousine Nerd Font Mono", style = "Bold Italic" }
italic = { family = "Cousine Nerd Font Mono", style = "Italic" }
size = 16

[cursor]
style = { blinking = "On" }
